# Generated by Django 3.0 on 2019-12-30 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191228_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_parents',
            name='UserType',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
