# Generated by Django 2.2.7 on 2020-01-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191228_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_parents',
            old_name='age',
            new_name='ChildGrade',
        ),
        migrations.AddField(
            model_name='user_parents',
            name='ChildID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
