# Generated by Django 3.0 on 2019-12-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_parents_utype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_parents',
            name='Usertype',
        ),
        migrations.AddField(
            model_name='user_teachers',
            name='Utype',
            field=models.CharField(default='teacher', max_length=200),
            preserve_default=False,
        ),
    ]
