# Generated by Django 2.2.7 on 2020-02-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200113_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_parents',
            name='UserType',
            field=models.CharField(default='parent', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_teachers',
            name='UserType',
            field=models.CharField(default='teacher', max_length=20),
        ),
    ]
