# Generated by Django 2.2.7 on 2020-03-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200214_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_teachers',
            name='schcode',
            field=models.CharField(default='school', max_length=20),
            preserve_default=False,
        ),
    ]
