# Generated by Django 2.2.7 on 2020-03-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_teachers_schcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_teachers',
            old_name='schcode',
            new_name='schoolCode',
        ),
    ]
