# Generated by Django 2.2.7 on 2020-02-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
