# Generated by Django 3.0 on 2020-01-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('roll', models.IntegerField()),
                ('childid', models.IntegerField()),
            ],
        ),
    ]
