# Generated by Django 3.0 on 2020-01-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0002_studentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('roll', models.IntegerField()),
                ('childid', models.IntegerField()),
                ('present_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='posts'),
        ),
    ]
