# Generated by Django 3.0 on 2020-01-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0004_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=30)),
                ('ten_ten45', models.CharField(max_length=30)),
                ('ten45_eleven30', models.CharField(max_length=30)),
                ('eleven45_twelve30', models.CharField(max_length=30)),
                ('twelve30_one15', models.CharField(max_length=30)),
                ('two_two45', models.CharField(max_length=30)),
                ('two45_three30', models.CharField(max_length=30)),
            ],
        ),
    ]
