# Generated by Django 2.2.7 on 2020-01-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0005_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='day',
            field=models.CharField(default='Sunday', max_length=40),
        ),
    ]
