# Generated by Django 2.2.7 on 2020-01-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0005_routine'),
        ('second', '0006_food_day'),
    ]

    operations = [
    ]
