# Generated by Django 2.2.7 on 2020-01-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0007_merge_20200108_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='remarks',
            field=models.CharField(default='Ate Well!', max_length=100),
        ),
    ]
