# Generated by Django 2.2.7 on 2020-01-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0008_food_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='childid',
        ),
        migrations.RemoveField(
            model_name='food',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='food',
            name='roll',
        ),
    ]
