# Generated by Django 2.2.7 on 2020-01-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0009_auto_20200108_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='day',
        ),
    ]
