# Generated by Django 2.2.7 on 2020-01-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0013_auto_20200108_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='full_name',
        ),
    ]
