# Generated by Django 2.2.7 on 2020-01-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0014_remove_food_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='day',
            field=models.CharField(default='Sunday', max_length=30),
        ),
    ]
