# Generated by Django 3.0 on 2020-01-25 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0016_auto_20200108_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absentday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second.StudentId')),
            ],
        ),
    ]
