# Generated by Django 2.2.7 on 2020-02-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0018_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
