# Generated by Django 3.0 on 2020-02-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0019_auto_20200202_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted']},
        ),
    ]
