# Generated by Django 3.0 on 2020-02-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0021_auto_20200204_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='absent_days',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='present_days',
        ),
        migrations.AddField(
            model_name='attendance',
            name='present_days_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
