# Generated by Django 2.2.7 on 2020-02-06 13:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0022_auto_20200204_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='childid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='eaten',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='full_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='noteaten',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Didnoteat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Ate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second.Food')),
            ],
        ),
    ]
