# Generated by Django 3.0 on 2020-02-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0023_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='slug',
            field=models.SlugField(default='notice'),
        ),
    ]
