# Generated by Django 3.0.2 on 2020-02-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0024_result_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='subject1',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
