# Generated by Django 3.0 on 2020-02-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0024_notice_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presentday',
        ),
    ]
