# Generated by Django 3.0.2 on 2020-02-11 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0027_auto_20200211_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second.Attendance'),
        ),
    ]
