# Generated by Django 2.2.7 on 2020-02-12 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0028_auto_20200211_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='remarks',
        ),
    ]
