# Generated by Django 3.0 on 2020-02-12 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0025_delete_presentday'),
        ('second', '0028_auto_20200211_0910'),
    ]

    operations = [
    ]
