# Generated by Django 3.0 on 2020-02-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0029_merge_20200212_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='slug',
        ),
    ]
