# Generated by Django 3.0.2 on 2020-02-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0029_merge_20200212_0509'),
        ('second', '0029_remove_food_remarks'),
    ]

    operations = [
    ]
