# Generated by Django 3.0 on 2020-02-13 14:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0030_remove_notice_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second.Attendance')),
            ],
        ),
    ]
