# Generated by Django 3.0 on 2020-02-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0030_merge_20200212_1220'),
        ('second', '0032_remove_attendance_present_days_count'),
    ]

    operations = [
    ]
