# Generated by Django 2.2.7 on 2020-02-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0023_auto_20200206_1920'),
        ('second', '0033_merge_20200213_1501'),
    ]

    operations = [
    ]
