# Generated by Django 2.2.7 on 2020-02-13 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('second', '0034_merge_20200213_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='SID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('roll', models.IntegerField()),
                ('childid', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='didnoteat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='food',
            name='childid',
        ),
        migrations.RemoveField(
            model_name='food',
            name='eaten',
        ),
        migrations.RemoveField(
            model_name='food',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='food',
            name='noteaten',
        ),
        migrations.DeleteModel(
            name='Ate',
        ),
        migrations.DeleteModel(
            name='Didnoteat',
        ),
    ]
