# Generated by Django 2.2.7 on 2020-02-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0036_auto_20200213_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch', models.CharField(max_length=50)),
            ],
        ),
    ]
