# Generated by Django 2.2.7 on 2020-03-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0038_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='schcode',
            field=models.CharField(default='school', max_length=20),
        ),
    ]
