# Generated by Django 2.2.7 on 2020-03-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0043_auto_20200311_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='name',
        ),
    ]
