# Generated by Django 2.2.7 on 2020-03-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0044_remove_contacts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='message',
            field=models.TextField(max_length=200),
        ),
    ]
