# Generated by Django 2.2.7 on 2020-03-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0045_auto_20200311_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='message',
            field=models.TextField(),
        ),
    ]
