# Generated by Django 3.0 on 2020-03-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0047_auto_20200315_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='result',
            name='remarks',
        ),
        migrations.AddField(
            model_name='result',
            name='term',
            field=models.TextField(default='empty', max_length=30),
            preserve_default=False,
        ),
    ]
